[tool.poetry]
name = "edusphere"
version = "0.1.0"
description = ""
authors = ["Robert Potemkin <rp00549@rvt.lv>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
channels-redis = "^4.3.0"
coverage = "^7.13.0"
dj-database-url = "^3.0.1"
django-cleanup = "^9.0.0"
django-cors-headers = "^4.9.0"
django-environ = "^0.12.0"
django-graphql-jwt = "^0.4.0"
djangorestframework = "^3.16.1"
graphene-file-upload = "^1.3.0"
httptools = "^0.7.1"
pillow = "^12.0.0"
psycopg2 = "^2.9.11"
pytest-django = "^4.11.1"
python-dotenv = "^1.2.1"
pyyaml = "^6.0.3"
sniffio = "^1.3.1"
uvicorn = "^0.40.0"
uvloop = "^0.22.1"
watchfiles = "^1.1.1"
websockets = "^15.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
